# foodadvisor/client/Dockerfile
FROM node:16 AS builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build

FROM node:16
WORKDIR /app
COPY --from=builder /app . 
EXPOSE 3000
ENV NODE_ENV=production
CMD ["yarn", "start"]

