# Use Node 16 as base image
FROM node:16

# Set working directory
WORKDIR /app

# 1) Copy only package files and install dependencies
COPY . .

RUN yarn install 

RUN yarn seed

RUN yarn build

# Expose port
EXPOSE 1337


CMD ["yarn", "develop"]