name: CI/CD Pipeline

# Run on push to main or pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      # 4.3.1 Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 4.3.2 Install Node.js (v18)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 4.3.3 Static code analysis with SonarCloud3
      - name: Before SonarCloud Scan
        run: echo "About to run SonarCloud"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: After SonarCloud Scan
        run: echo "Finished SonarCloud step"

      

      # 4.3.4 Build Strapi backend image
      - name: Build backend container
        run: docker build -t foodadvisor-backend:latest ./api

      # 4.3.5 Build Next.js frontend image
      - name: Build frontend container
        run: docker build -t foodadvisor-frontend:latest ./client

      # 4.3.6 Scan backend image for vulnerabilities
      
      # 4.3.7 Scan frontend image for vulnerabilities
          
      # 4.4.1 Log in to Docker Hub
      - name: Docker Hub login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
            docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 4.4.2 Tag and push both images
      - name: Push containers to registry
        run: |
        
          docker tag foodadvisor-backend:latest \
            ${{ secrets.DOCKER_USERNAME }}/foodadvisor-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/foodadvisor-backend:latest
          docker tag foodadvisor-frontend:latest \
            ${{ secrets.DOCKER_USERNAME }}/foodadvisor-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/foodadvisor-frontend:latest
